services:

  argilla:
    image: argilla/argilla-server@sha256:24b114e7e4e1fc977a8570750446afc6ba585f111e5b4306229447a1862dc5f1
    restart: unless-stopped
    ports:
      - "6900:6900"
    environment:
      ARGILLA_HOME_PATH: /var/lib/argilla
      ARGILLA_ELASTICSEARCH: http://elasticsearch:9200
      ARGILLA_AUTH_SECRET_KEY: ${ARGILLA_AUTH_SECRET_KEY:? Please generate a 32 character random string with `openssl rand -hex 32`}

      ARGILLA_ENABLE_TELEMETRY: 0 # Opt-out for telemetry https://docs.argilla.io/en/latest/reference/telemetry.html

      # Set user configuration (no public docs for pinned version): https://github.com/argilla-io/argilla-server/blob/6130c634506bc649a64d8461992946537ae287e1/src/argilla_server/cli/database/users/migrate.py#L90
      ARGILLA_LOCAL_AUTH_USERS_DB_FILE: /config/.users.yaml
      USERS_DB: /config/.users.yaml
      
      
      DEFAULT_USER_ENABLED: false
      # DEFAULT_USER_PASSWORD: ${DEFAULT_USER_PASSWORD:? Please set a new password for the default user.}
      # DEFAULT_USER_API_KEY: ${DEFAULT_USER_API_KEY:? Please set a new api key for the default user.}
    networks:
      - argilla
    volumes:
      # ARGILLA_HOME_PATH is used to define where Argilla will save it's application data.
      # If you change ARGILLA_HOME_PATH value please copy that same value to argilladata volume too.
      - argilladata:/var/lib/argilla
      - ${PWD}/.users.yaml:/config/.users.yaml
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    environment:
      - node.name=elasticsearch
      - cluster.name=es-argilla-local
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.routing.allocation.disk.threshold_enabled=false
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - argilla
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticdata:/usr/share/elasticsearch/data/
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.5.3
  #   ports:
  #     - "5601:5601"
  #   environment:
  #     ELASTICSEARCH_URL: http://elasticsearch:9200
  #     ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
  #   networks:
  #     - argilla

networks:
  argilla:
    driver: bridge
volumes:
  argilladata:
  elasticdata:
